name: Run Unit Test via Pytest

on: workflow_dispatch

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        run: |
          poetry install
      - name: Install playwright
        run: poetry run playwright install --with-deps
      - name: Run tests with pytest
        run: |
           poetry run pytest --browser ${{ matrix.browser }} --tracing on

      - name: Upload Playwright trace artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces-${{ matrix.browser }}
          path: test-results

